#:kivy 1.11.1
<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width,root.height
        padding: 50
        spacing: 20

        Button:
            text: "Hello World"
            font_size : 32
        
        Button:
            text: "Button 2"

        Button:
            text: "Button 3"
            pos_hint :{"center_x":0.5}
            size_hint :(0.5,0.5)
            # width: 500
            # height: 10